/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.28                          *
*        Compiled Jan 30 2015, 16:41:06                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "FramewinDLG.h"
#include "Medicinechildern.h"
#include <stdlib.h>

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0    (GUI_ID_USER + 0x00)
#define ID_TEXT_0    (GUI_ID_USER + 0x01)
#define ID_EDIT_0    (GUI_ID_USER + 0x02)
#define ID_TEXT_1    (GUI_ID_USER + 0x03)
#define ID_DROPDOWN_0    (GUI_ID_USER + 0x0E)
#define ID_DROPDOWN_1    (GUI_ID_USER + 0x0F)
#define ID_DROPDOWN_2    (GUI_ID_USER + 0x10)
#define ID_DROPDOWN_3    (GUI_ID_USER + 0x11)
#define ID_DROPDOWN_4    (GUI_ID_USER + 0x12)
#define ID_MULTIEDIT_0    (GUI_ID_USER + 0x14)
#define ID_BUTTON_0 (GUI_ID_USER + 0x15)
#define ID_BUTTON_1 (GUI_ID_USER + 0x16)



static	WM_HWIN hwin1;
static int i;
static int in;

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 20, 61, 91, 36, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 139, 60, 101, 37, 0, 0xc8, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 18, 153, 80, 20, 0, 0x64, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_0, 106, 158, 100, 150, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_1, 215, 159, 80, 150, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_2, 317, 161, 80, 150, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_3, 105, 239, 80, 120, 0, 0x0, 0 },
  { DROPDOWN_CreateIndirect, "Dropdown", ID_DROPDOWN_4, 212, 238, 80, 120, 0, 0x0, 0 },
  { MULTIEDIT_CreateIndirect, "Multiedit", ID_MULTIEDIT_0, 465, 52, 218, 316, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 600, 400, 100, 40, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 450, 400, 100, 40, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};






// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/





static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
	WM_HWIN hItem_edit;
	WM_HWIN hItem_Drop_Years;
  int     NCode;
  int     Id;
	char * dropString;
	int DropdownSecItemNum;
  // USER START (Optionally insert additional variables)
  // USER END
	char out[10];

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
		

	hItem = pMsg->hWin;
	FRAMEWIN_SetText(hItem,"medicine");
	FRAMEWIN_SetFont(hItem, GUI_FONT_24_ASCII);
	FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem, "medicineName");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'Edit'
    //
    hItem_edit = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem_edit, "name");
    EDIT_SetTextAlign(hItem_edit, GUI_TA_HCENTER | GUI_TA_VCENTER);
		EDIT_SetFont(hItem_edit, GUI_FONT_13B_1);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetText(hItem, "Timing");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
		TEXT_SetFont(hItem, GUI_FONT_13B_1);
    //
    // Initialization of 'Listbox'
    //
    hItem_Drop_Years = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_0);						
		DROPDOWN_SetAutoScroll(hItem_Drop_Years,1);
    DROPDOWN_AddString(hItem_Drop_Years, "2015");
		for (i = 0; i <50; i++){
			in= 2016 + i;
			//sprintf(in,"%s",out);
			sprintf(out, " %d" , in);
			DROPDOWN_AddString(hItem_Drop_Years, out);
			DROPDOWN_SetFont(hItem_Drop_Years, GUI_FONT_13B_1);
			DropdownSecItemNum = DROPDOWN_GetSel(hItem_Drop_Years);
			sprintf(dropString, " %d" , DropdownSecItemNum);
		}


		
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_1);
		DROPDOWN_SetAutoScroll(hItem,1);
		for (i = 0; i <12; i++){
			in= 1 + i;
			sprintf(out, " %d" , in);
			DROPDOWN_AddString(hItem, out);
			DROPDOWN_SetFont(hItem, GUI_FONT_13B_1);
		}
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_2);
		DROPDOWN_SetAutoScroll(hItem,1);
		for (i = 0; i <31; i++){
			in= 1 + i;
			sprintf(out, " %d" , in);
			DROPDOWN_AddString(hItem, out);
			DROPDOWN_SetFont(hItem, GUI_FONT_13B_1);
		}
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_3);
		DROPDOWN_SetAutoScroll(hItem,1);
    for (i = 0; i <24; i++){
			in= 1 + i;
			sprintf(out, " %d" , in);
			DROPDOWN_AddString(hItem, out);
			DROPDOWN_SetFont(hItem, GUI_FONT_13B_1);
		}
    //
    // Initialization of 'Listbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DROPDOWN_4);
		DROPDOWN_SetAutoScroll(hItem,1);
    for (i = 0; i <60; i++){
			in= 1 + i;
			sprintf(out, " %d" , in);
			DROPDOWN_AddString(hItem, out);
			DROPDOWN_SetFont(hItem, GUI_FONT_13B_1);
		}
    //
    // Initialization of 'Multiedit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_0);
    MULTIEDIT_SetText(hItem, "goods infomation");
		MULTIEDIT_SetFont(hItem, GUI_FONT_13B_1);
		
		//button0
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
		BUTTON_SetFont(hItem, GUI_FONT_13B_1);
    BUTTON_SetText(hItem, "back");
		
		//button1
		hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
		BUTTON_SetFont(hItem, GUI_FONT_13B_1);
    BUTTON_SetText(hItem, "submit");
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_EDIT_0: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_0: // Notifications sent by 'Listbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:

        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:

						
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_1: // Notifications sent by 'Listbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
				
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_2: // Notifications sent by 'Listbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_3: // Notifications sent by 'Listbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_DROPDOWN_4: // Notifications sent by 'Listbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_MULTIEDIT_0: // Notifications sent by 'Multiedit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
		case ID_BUTTON_0: // Notifications sent by 'Multiedit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				FRAMEWIN_Delete(hwin1);
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
			
			// submit°´Å¥
			case ID_BUTTON_1: // Notifications sent by 'submit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
				
				EDIT_SetText (hItem_edit,dropString);
				//Medicine_Childer_Window();
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
				
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}




/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/

WM_HWIN CreateFramewin(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}



void TakeMedicine_Window(void)
{

	hwin1 = CreateFramewin();
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
